import './globals.css'
import { Playfair_Display } from 'next/font/google'
// import { Helvetica } from 'next/font/google'

const playfair = Playfair_Display({ subsets: ['latin'] })
// const helvetica = Helvetica({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>{children}</body>
      {/* <body className={helvetica.className}>{children}</body> */}
    </html>
  )
}
